### ISSUE TITLE
重新提交存廢補模板時沒有為模板空間補上noinclude

### ISSUE THREAD

**Issue by Xi-Plus** [xiplus-mediawiki-programs/twinkle#305]
https://zh.wikipedia.org/w/index.php?diff=84636915

**Comment by hamishzx** [comment]
以及其实该页面内有提删模板，但tw识别为没有。同样的情况也出现在条目空间内[https://zh.wikipedia.org/w/index.php?diff=84609589](https://zh.wikipedia.org/w/index.php?diff=84609589)

**Comment by Xi-Plus** [comment]
garbage in garbage out

**Comment by hamishzx** [comment]
> garbage in garbage out

lol
